### ISSUE TITLE
No rendering

### ISSUE THREAD

**Issue by michaelnatkin** [zzyunzhi/scene-language#4]
I'm sure I'm doing something perfectly silly, but when I run:

`python scripts/run.py --tasks  "a statue of a pizza"`

It appears to work and generates the output directory with 4 attempts, each with a program.py. But it never seems to call mitsuba to render the results, there is no renderings subdirectory. On mac M1 if that helps. I tested that mitsuba itself is installed and working, rendered one of its test files. Any pointers much appreciated!

**Comment by michaelnatkin** [comment]
Hmm.. well I figured out that I need to run `scripts/postprocess.render.py` (should probably add that to the readme), and that I needed to `pip install tqdm`, but now the error log shows ```Traceback (most recent call last):
  File "/tmp/impl.py", line 17, in <module>
    import mi_helper  # such that primitive call will be implemented
    ^^^^^^^^^^^^^^^^
  File "/Users/michael/code/scene-language/scripts/prompts/mi_helper.py", line 79, in <module>
    sensors: dict[str, mi.Sensor],
                       ^^^^^^^^^
AttributeError: module 'mitsuba' has no attribute 'Sensor'```

**Comment by zzyunzhi** [comment]
Could you please try `pip install --force-reinstall mitsuba==3.5.1`? After reinstallation, the following is supposed to run without error:
```python
import mitsuba as mi
mi.set_variant('scalar_rgb')
print(mi.Sensor)
```

**Comment by michaelnatkin** [comment]
That worked, thank you!!!
